// Auto-generated by scripts/optimize-images.mjs — do not edit manually.
// Regenerate: npm run optimize-images

export interface SiteImage {
  /** Unique SEO slug (also the filename base) */
  slug: string;
  /** Service folder the image belongs to */
  service: string;
  /** Pre-built alt text for <img alt="..."> */
  alt: string;
  /** Pixel widths of available WebP variants */
  widths: number[];
  /** Size profile used during generation */
  profile: 'hero' | 'gallery' | 'og' | 'thumb';
  /** Canonical src (largest variant) */
  src: string;
  /** Ready-to-use srcset string for <img srcset="..."> */
  srcset: string;
}

export const SITE_IMAGES: readonly SiteImage[] = [
  {
    "slug": "gallery-audi-tt-urmston-latin-king-detailing-01",
    "service": "gallery",
    "alt": "Audi TT RS in Sepang Blue front three-quarter view after ceramic coating by Latin King Detailing",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-audi-tt-urmston-latin-king-detailing-01-1280w.webp",
    "srcset": "/images/gallery/gallery-audi-tt-urmston-latin-king-detailing-01-1280w.webp 1280w, /images/gallery/gallery-audi-tt-urmston-latin-king-detailing-01-800w.webp 800w, /images/gallery/gallery-audi-tt-urmston-latin-king-detailing-01-480w.webp 480w"
  },
  {
    "slug": "gallery-audi-tt-urmston-latin-king-detailing-02",
    "service": "gallery",
    "alt": "Audi TT RS rear profile showing gloss finish after detailing by Latin King Detailing, Urmston",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-audi-tt-urmston-latin-king-detailing-02-1280w.webp",
    "srcset": "/images/gallery/gallery-audi-tt-urmston-latin-king-detailing-02-1280w.webp 1280w, /images/gallery/gallery-audi-tt-urmston-latin-king-detailing-02-800w.webp 800w, /images/gallery/gallery-audi-tt-urmston-latin-king-detailing-02-480w.webp 480w"
  },
  {
    "slug": "gallery-audi-tt-urmston-latin-king-detailing-03",
    "service": "gallery",
    "alt": "Audi TT RS straight-on front view showcasing deep gloss after full detail by Latin King Detailing",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-audi-tt-urmston-latin-king-detailing-03-1280w.webp",
    "srcset": "/images/gallery/gallery-audi-tt-urmston-latin-king-detailing-03-1280w.webp 1280w, /images/gallery/gallery-audi-tt-urmston-latin-king-detailing-03-800w.webp 800w, /images/gallery/gallery-audi-tt-urmston-latin-king-detailing-03-480w.webp 480w"
  },
  {
    "slug": "gallery-ferrari-12cilindri-urmston-latin-king-detailing-04",
    "service": "gallery",
    "alt": "Ferrari 12Cilindri front detail after mobile car wash by Latin King Detailing",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-04-1280w.webp",
    "srcset": "/images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-04-1280w.webp 1280w, /images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-04-800w.webp 800w, /images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-04-480w.webp 480w"
  },
  {
    "slug": "gallery-ferrari-12cilindri-urmston-latin-king-detailing-05",
    "service": "gallery",
    "alt": "Ferrari 12Cilindri rear three-quarter view, mobile valet by Latin King Detailing",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-05-1280w.webp",
    "srcset": "/images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-05-1280w.webp 1280w, /images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-05-800w.webp 800w, /images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-05-480w.webp 480w"
  },
  {
    "slug": "gallery-ferrari-12cilindri-urmston-latin-king-detailing-06",
    "service": "gallery",
    "alt": "Ferrari 12Cilindri side profile during detailing by Latin King Detailing, Urmston",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-06-1280w.webp",
    "srcset": "/images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-06-1280w.webp 1280w, /images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-06-800w.webp 800w, /images/gallery/gallery-ferrari-12cilindri-urmston-latin-king-detailing-06-480w.webp 480w"
  },
  {
    "slug": "gallery-ferrari-purosangue-urmston-latin-king-detailing-07",
    "service": "gallery",
    "alt": "Ferrari Purosangue exterior detail by Latin King Detailing, mobile car care Urmston",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-07-1280w.webp",
    "srcset": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-07-1280w.webp 1280w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-07-800w.webp 800w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-07-480w.webp 480w"
  },
  {
    "slug": "gallery-ferrari-purosangue-urmston-latin-king-detailing-08",
    "service": "gallery",
    "alt": "Ferrari Purosangue paintwork after mobile valet by Latin King Detailing, Urmston",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-08-1280w.webp",
    "srcset": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-08-1280w.webp 1280w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-08-800w.webp 800w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-08-480w.webp 480w"
  },
  {
    "slug": "gallery-ferrari-purosangue-urmston-latin-king-detailing-09",
    "service": "gallery",
    "alt": "Ferrari Purosangue full exterior detail by Latin King Detailing, Urmston, Greater Manchester",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-09-1280w.webp",
    "srcset": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-09-1280w.webp 1280w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-09-800w.webp 800w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-09-480w.webp 480w"
  },
  {
    "slug": "gallery-ferrari-purosangue-urmston-latin-king-detailing-10",
    "service": "gallery",
    "alt": "Ferrari Purosangue carbon fibre steering wheel and interior after interior detail by Latin King Detailing",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-10-1280w.webp",
    "srcset": "/images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-10-1280w.webp 1280w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-10-800w.webp 800w, /images/gallery/gallery-ferrari-purosangue-urmston-latin-king-detailing-10-480w.webp 480w"
  },
  {
    "slug": "gallery-ford-mustang-bullitt-urmston-latin-king-detailing-11",
    "service": "gallery",
    "alt": "Ford Mustang Bullitt Bullitt Edition mobile car wash by Latin King Detailing, Urmston",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-11-1280w.webp",
    "srcset": "/images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-11-1280w.webp 1280w, /images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-11-800w.webp 800w, /images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-11-480w.webp 480w"
  },
  {
    "slug": "gallery-ford-mustang-bullitt-urmston-latin-king-detailing-12",
    "service": "gallery",
    "alt": "Ford Mustang Bullitt side view during mobile detailing by Latin King Detailing",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-12-1280w.webp",
    "srcset": "/images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-12-1280w.webp 1280w, /images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-12-800w.webp 800w, /images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-12-480w.webp 480w"
  },
  {
    "slug": "gallery-ford-mustang-bullitt-urmston-latin-king-detailing-13",
    "service": "gallery",
    "alt": "Ford Mustang Bullitt Bullitt Edition after full exterior valet by Latin King Detailing, Urmston",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-13-1280w.webp",
    "srcset": "/images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-13-1280w.webp 1280w, /images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-13-800w.webp 800w, /images/gallery/gallery-ford-mustang-bullitt-urmston-latin-king-detailing-13-480w.webp 480w"
  },
  {
    "slug": "interior-urmston-latin-king-detailing-01",
    "service": "interior",
    "alt": "Car accelerator pedal after interior deep clean by Latin King Detailing — restored to clean, like-new condition",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/interior/interior-urmston-latin-king-detailing-01-1280w.webp",
    "srcset": "/images/interior/interior-urmston-latin-king-detailing-01-1280w.webp 1280w, /images/interior/interior-urmston-latin-king-detailing-01-800w.webp 800w, /images/interior/interior-urmston-latin-king-detailing-01-480w.webp 480w"
  },
  {
    "slug": "interior-urmston-latin-king-detailing-02",
    "service": "interior",
    "alt": "Car interior footwell after interior deep clean by Latin King Detailing, Urmston — spotlessly clean floor mat and polished pedals",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/interior/interior-urmston-latin-king-detailing-02-1280w.webp",
    "srcset": "/images/interior/interior-urmston-latin-king-detailing-02-1280w.webp 1280w, /images/interior/interior-urmston-latin-king-detailing-02-800w.webp 800w, /images/interior/interior-urmston-latin-king-detailing-02-480w.webp 480w"
  },
  {
    "slug": "interior-urmston-latin-king-detailing-03",
    "service": "interior",
    "alt": "Car accelerator pedal before interior detailing — heavily worn and contaminated with salt deposits and grime",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/interior/interior-urmston-latin-king-detailing-03-1280w.webp",
    "srcset": "/images/interior/interior-urmston-latin-king-detailing-03-1280w.webp 1280w, /images/interior/interior-urmston-latin-king-detailing-03-800w.webp 800w, /images/interior/interior-urmston-latin-king-detailing-03-480w.webp 480w"
  },
  {
    "slug": "interior-urmston-latin-king-detailing-04",
    "service": "interior",
    "alt": "Car interior footwell before deep cleaning by Latin King Detailing — heavy salt and dirt contamination on floor mat and pedals",
    "widths": [
      1280,
      800,
      480
    ],
    "profile": "gallery",
    "src": "/images/interior/interior-urmston-latin-king-detailing-04-1280w.webp",
    "srcset": "/images/interior/interior-urmston-latin-king-detailing-04-1280w.webp 1280w, /images/interior/interior-urmston-latin-king-detailing-04-800w.webp 800w, /images/interior/interior-urmston-latin-king-detailing-04-480w.webp 480w"
  }
] as const;

/** Return all images for a given service slug */
export function getImagesByService(service: string): SiteImage[] {
  return SITE_IMAGES.filter((img) => img.service === service);
}

/** Return the first hero-profile image for a service, or the first image overall */
export function getHeroImage(service?: string): SiteImage | undefined {
  const pool = service ? getImagesByService(service) : [...SITE_IMAGES];
  return pool.find((img) => img.profile === 'hero') ?? pool[0];
}

/** Return all gallery images, optionally filtered by service */
export function getGalleryImages(service?: string): SiteImage[] {
  const pool = service ? getImagesByService(service) : [...SITE_IMAGES];
  return pool.filter((img) => img.profile === 'gallery');
}
